# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://merriam.github.io/nb_bagels/"

git_url = "https://github.com/merriam/nb_bagels/tree/master/"

def custom_doc_links(name): return None
